dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install poetry
  - poetry install
script:
  - pipenv run pytest
after_success:
  - codecov
notifications:
  - email: false
